export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const OVERWRITE_CURRENT_USER = "OVERWRITE_CURRENT_USER";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_USER_POSTS = "GET_USER_POSTS";

export const GET_JOIN_REQUEST_NOTIFICATIONS = "GET_JOIN_REQUEST_NOTIFICATIONS";
