/*export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const OVERWRITE_CURRENT_USER = "OVERWRITE_CURRENT_USER";
export const INSERT_EVENT_INFO = "INSERT_EVENT_INFO";
export const EMPTY_EVENT_INFO = "EMPTY_EVENT_INFO";
export const CLEAN_UP = "CLEAN_UP";
export const GET_CURRENT_MESSAGES = "GET_CURRENT_MESSAGES";
export const GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS";//*/

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
